config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'admin/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, :only => [:index, :show] do
    member do
      get :wanted
      get :owned
    end
  end

  resources :games do
    member do
      get :wishers
      get :owners
    end
  end

  resources :wishlists,  :only => [:create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  
  resources :platforms,  :only => [:index] do
    collection do
      get :threeds, path: "3ds"
      get :gamecube
      get :pc
      get :playstation_2, path: "playstation-2"
      get :playstation_3, path: "playstation-3"
      get :playstation_4, path: "playstation-4"
      get :wii
      get :wii_u, path: "wii-u"
      get :xbox
      get :xbox_360, path: "xbox-360"
      get :xbox_one, path: "xbox-one"
    end
  end

  root 'main#index'
  match '/platform/:platform', to: 'main#index', via: 'get'

  get 'games/:id/edit'     => 'games#edit',     as: :edit
  get 'games/:id/wanted'   => 'games#wishers',  as: :game_wanted
  get 'games/:id/owned'    => 'games#owners',   as: :game_owners
  get 'admin/'             => 'admin#index',    as: :admin

end

app/views/shared/_games_table.html.erb
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable "platform" %></th>
      <th><%= sortable "genre" %></th>
      <th><%= sortable "year" %></th>
      <th><%= sortable game_table_column(params[:action]) %></th>
    </tr>
  </thead>
  <tbody>
     <%= render @games %>
  </tbody>
</table>

app/views/shared/_new_edit_form.html.erb
<%= simple_form_for(@game, html: {class: 'form-horizontal' },
        # wrapper: :horizontal_form,
        wrapper_mappings: {
        check_boxes: :horizontal_radio_and_checkboxes,
        radio_buttons: :horizontal_radio_and_checkboxes,
        file: :horizontal_file_input,
        boolean: :horizontal_boolean
    }) do |f| %>

    <%= f.error_notification %>
    
    <%= f.input :name %>
    <%= f.input :year %>
    <%= f.input :description %>
    <%= f.input :genre %>

    <%= link_to "Cancel", :back, class: "btn btn-default pull-right btn-cancel" %>
    <%= f.submit "Submit", class: "btn btn-primary pull-right" %>
<% end %>

<div class="clearfix"></div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <div>
    <a href="<%= wanted_user_path(@user) %>">
    <strong id="wished" class="stat">
      <%= @user.wanted.count %>
    </strong>
    wanted</a>
  </div>
  <div>
    <a href="<%= owned_user_path(@user) %>">
    <strong id="owned" class="stat">
      <%= @user.owned.count %>
    </strong>
    owned</a>
  </div>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 36), current_user %>

app/views/shared/_user_section.html.erb
<% if user_signed_in? %>
  <section id="user-info">
    <%= render 'shared/user_info' %>
    <%#= render 'shared/stats' %>
  </section>
<% end %>