config/routes.rb
Rails.application.routes.draw do
  get 'main/index'
  get 'admin/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  resources :users, :only => [:index, :show] do
    member do
      get :wanted
      get :owned
    end
  end

  resources :games do
    member do
      get :wishers
      get :owners
    end
  end

  resources :wishlists,  :only => [:create, :destroy]
  resources :ownerships, :only => [:create, :destroy]
  
  resources :platforms,  :only => [:index] do
    collection do
      get :threeds, path: "3ds"
      get :gamecube
      get :pc
      get :playstation_2, path: "playstation-2"
      get :playstation_3, path: "playstation-3"
      get :playstation_4, path: "playstation-4"
      get :wii
      get :wii_u, path: "wii-u"
      get :xbox
      get :xbox_360, path: "xbox-360"
      get :xbox_one, path: "xbox-one"
    end
  end

  root 'main#index'
  match '/platform/:platform', to: 'main#index', via: 'get'

  get 'games/:id/edit'     => 'games#edit',     as: :edit
  get 'games/:id/wanted'   => 'games#wishers',  as: :game_wanted
  get 'games/:id/owned'    => 'games#owners',   as: :game_owners
  get 'admin/'             => 'admin#index',    as: :admin

end

app/views/layouts/_about.html.erb
<section class="about">
  <h3>What is this?</h3>

  <p>
    The video game industry is growing at an incredible pace. In 2014, the industry is expected to hit <%= link_to "$100 billion", "http://www.gartner.com/newsroom/id/2614915" %>. In the US alone, <%= link_to "59% of Americans", "http://www.theesa.com/facts/pdfs/esa_ef_2014.pdf" %> are playing video games. As a result, games are released at such a rapid pace that it's easy to miss out on some incredible experiences. Likewise, gamers have a vast library of games at their disposal. These games span a number of years across a multitude of platforms. Many are ground breaking, unforgettable and leave a lasting impression.
  </p>

  <p>
    Great Games Club is an attempt at cataloging great games throughout the years. These are the games that have left an impact on gamers and deserve to be remembered, played and enjoyed.
  </p>

  <p>
    Clicking on a game will give you more information about it, such as the publisher, developer, Metacritic score, popular YouTube videos and pricing information from Amazon. Prices are updated daily and games are being added regularly!
  </p>
</section>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-header">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Great Games Club', root_url, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-header">
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav">
        <li><%= link_to "All", games_path %></li>
        <li><%= link_to "PC", pc_platforms_path, class: "pc" %></li>
        <li><%= link_to "Playstation 4", playstation_4_platforms_path, class: "playstation-4" %></li>
        <li><%= link_to "Wii U", wii_u_platforms_path, class: "wii-u" %></li>
        <li><%= link_to "Xbox One", xbox_one_platforms_path, class: "xbox-one" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">More <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "3DS", threeds_platforms_path %></li>
            <li><%= link_to "Gamecube", gamecube_platforms_path %></li>
            <li><%= link_to "Playstation 2", playstation_2_platforms_path %></li>
            <li><%= link_to "Playstation 3", playstation_3_platforms_path %></li>
            <li><%= link_to "Wii", wii_platforms_path %></li>
            <li><%= link_to "Xbox", xbox_platforms_path %></li>
            <li><%= link_to "Xbox 360", xbox_360_platforms_path %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "Admin".html_safe, admin_path %> </li>
          <% end %>
          <li><%= render 'shared/user_section' %></li>
          <li><%= link_to "Sign Out".html_safe, destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up".html_safe, new_user_registration_path %> </li>
          <li><%= link_to "Sign In".html_safe, new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_header_ad.html.erb
<% if Rails.env.production? %>
    <div class="text-center ad-margin">
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- GClub Header -->
        <ins class="adsbygoogle"
             style="display:block"
             data-ad-client="ca-pub-1030633282804595"
             data-ad-slot="7331993530"
             data-ad-format="auto"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
<% end %>

app/views/layouts/_mid_ad.html.erb
<% if Rails.env.production? %>
  <div class="text-center ad-margin">
      <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
      <!-- GClub Mid -->
      <ins class="adsbygoogle"
           style="display:block"
           data-ad-client="ca-pub-1030633282804595"
           data-ad-slot="4661373136"
           data-ad-format="auto"></ins>
      <script>
      (adsbygoogle = window.adsbygoogle || []).push({});
      </script>
  </div>
<% end %>

app/views/layouts/_vertical_ad.html.erb
<% if Rails.env.production? %>
  <div class="ad-margin">
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- GClub Vertical -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-1030633282804595"
         data-ad-slot="4250442737"
         data-ad-format="auto"></ins>
    <script>
    (adsbygoogle = window.adsbygoogle || []).push({});
    </script>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Roboto:400,700' %>
  <%= stylesheet_link_tag    'application', 'http://fonts.googleapis.com/css?family=Lato:400,700' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <% if current_page?('/') %>
    <meta name="description" content="Cataloging great games that deserve to be remembered, played and enjoyed.">
  <% end %>

  <!-- Facebook Open Graph Info -->
  <meta property="og:title" content="Great Games Club" />
  <meta property="og:url" content="http://greatgames.club/" />
  <meta property="og:description" content="Cataloging great games that deserve to be remembered, played and enjoyed." />
  <meta property="og:image" content="" />
  <!-- End Facebook Open Graph Info -->

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-9342343-3', 'greatgames.club');
    ga('require', 'displayfeatures');
    ga('send', 'pageview');
  </script>
</head>
<body>

<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '785877794758034',
      xfbml      : true,
      version    : 'v2.0'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

<%= render 'layouts/header' %>

<div class="container">
  <%= render 'layouts/header_ad' %>
  
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  
  <%= yield %>

  <%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>